version: '3.8'

services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: cryptopolis_db
    shm_size: 256mb
    environment:
      POSTGRES_PASSWORD: cryptopolis
      POSTGRES_USER: cryptopolis
      POSTGRES_DB: cryptopolis
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - cryptopolis_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cryptopolis"]
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer:4.8.1
    restart: unless-stopped
    container_name: cryptopolis_adminer
    ports:
      - "8080:8080"
    networks:
      - cryptopolis_network
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  cryptopolis_network:
    driver: bridge
